### ISSUE TITLE
Add "Higher than Average" qualifier to earnings chart

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1066]
![image](https://cloud.githubusercontent.com/assets/12847090/9696298/99fb2b60-533b-11e5-9454-415d9fb99259.png)

**Comment by jjoteal** [comment]
FYI -- It will certainly help once we get the label and tooltip in place here. It will also help when we add the "Higher than Average" qualifier item to the bottom.

Additionally, the circle graphic filled this space nicely, but that was de-prioritized for launch because it would take some development work to implement. Here was the original design for reference:

![image](https://cloud.githubusercontent.com/assets/12192706/9696340/38c51b3e-533c-11e5-8b7d-e13ea4ef120e.png)

**Comment by jjoteal** [comment]
@meiqimichelle so per my comment above, for the MVP, I recommend that we add the label and the tooltip as well as the "Higher than Average" indicator and that should fill the space nicely for launch.

We can deal with the circle graphic after launch of course.

**Comment by meiqimichelle** [comment]
@jjoteal what do you mean by label? I did add the tooltip. Adding the 'higher than average' is a Shawn thing tho :( We should chat to see if there's any way to fill that space easily.

**Comment by jjoteal** [comment]
Just closing the loop here. What you've done, @meiqimichelle is correct (label + tooltip).

Leaving this open for @shawnbot to add the "above average" indicator though.

**Comment by barkimedes** [comment]
@jjoteal This can be closed, correct? I see the "Higher than average" notes on the scorecard on production.
