### ISSUE TITLE
marvel and kibana have helath status yellow, should be greeen?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1074]
https://ed-staging-eservice-proxy.18f.gov/_cat/indices?v

```
health status index                  pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   .marvel-2015.09.05       1   1      23153            0       37mb           37mb 
green  open   production-school-data   1   0       7805         2327    439.3mb        439.3mb 
yellow open   .marvel-kibana           1   1          1            0      3.2kb          3.2kb 
```

**Comment by ultrasaurus** [comment]
@ozzyjohnson not sure what these health status indicators mean, but wondering if they shouild be green

**Comment by ozzyjohnson** [comment]
At a glance...

When Marvel creates its indices it's requesting 1/1 shards/replicas. Since the service instances are single nodes that replica will never be assigned as a replica can only be assigned to a node other the primary. The production-school-data is green because it's requesting 1/0.

On a related note, can you bump the index creation request up to create more shards? The default is 5 and we should be able to better performance with at least 2.

**Comment by ultrasaurus** [comment]
Maybe we actually need fewer shards...  tracking in separate issue here:  https://github.com/18F/college-choice/issues/1081

**Comment by ultrasaurus** [comment]
thanks @ozzyjohnson -- I've added your note to the docs: https://github.com/18F/college-choice-data/commit/6f84c7344d4ebbafe6600222677937322bdb3a26
