### ISSUE TITLE
Get The Best Deal on the School page should be styled more like the HP

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1124]
Title should be centered and larger than the text on the buttons.
![screen shot 2015-09-06 at 8 17 33 pm](https://cloud.githubusercontent.com/assets/12847090/9707373/5eeb3304-54d4-11e5-8ee2-577b5fd3decc.png)
![screen shot 2015-09-06 at 8 17 11 pm](https://cloud.githubusercontent.com/assets/12847090/9707374/5eef1e9c-54d4-11e5-95b3-077236ce9901.png)

@jjoteal may have already addressed with another ticket?

**Comment by ErieMeyer** [comment]
FWIW, in testing today, the tester would do a search and then start clicking on "estimate your aid" instead of the school-specific net price calculator. I wonder if we shouldn't drop the sidebar implementation on the interior pages and instead just keep the homepage version (in case the person doesn't want to dig in).

**Comment by jjoteal** [comment]
Not sure I'm completely following, but the screenshots above are the correct design implementation on the individual school page. If you want, we could put things in a white container vs. directly on the light gray background, but that would be a change that Michelle would need to make.

**Comment by jjoteal** [comment]
Closing this issue as it seems to be resolved.
