### ISSUE TITLE
Improve performance (queries per second) of open data maker application

### ISSUE THREAD

**Issue by yozlet** [18F/college-choice#1201]
- [x] validate that caching works for api.data.gov
- [x] scale elasticsearch vertically, try a 2x large and/or 3x large  (ex space @dnesting )
- [ ] using connection pooling in the elasticsearch client  (indexing space @yoz)
- [ ] create a cluster with replicas

not a priority: shards (since we're readonly after first indexing), depends on https://github.com/18F/open-data-maker/issues/204

**Comment by hollyallen** [comment]
@yozlet and @dnesting have been testing with multi-process Unicorn. 
The next thing they are going to try is switching from Unicorn to Puma and seeing if that helps the number of queries per second the server can handle.

**Comment by hollyallen** [comment]
Aiming to stop optimizing this by end of day today, then code freeze, testing, and  and production deployment.

**Comment by dnesting** [comment]
Load testing results are in issue #597 and look much better.  I'm about to create a PR with my changes.

**Comment by LisaGee** [comment]
yay!

**Comment by barkimedes** [comment]
@dnesting What's next for this issue?

**Comment by dnesting** [comment]
@barkimedes I think the checklist in the first comment sums it up, but we've launched since the time this issue was created and I think we are generally satisfied with the performance of the system and its ability to scale beyond what we originally wanted to figure out.  Sooo I'm OK closing this early unless someone thinks we want to put some time into the other scaling options.

**Comment by hollyallen** [comment]
Concur. The uncompleted tasks in the checklist represent potential future performance improvement methods should performance become a problem.
