### ISSUE TITLE
substring search on name of college is very slow

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1225]
Improve performance (query latency) of elasticsearch generally, and especially of substring search.

**Comment by ultrasaurus** [comment]
https://ccapi-staging.18f.gov/v1/schools?sort=2011.earnings.6_yrs_after_entry.percent_greater_than_25000%3Adesc&school.name=arizona&school.degrees_awarded.predominant__range=2..3&school.operating=1&fields=id%2Cschool.name%2Cschool.city%2Cschool.state%2C2013.student.size%2Cschool.ownership%2Cschool.degrees_awarded.predominant%2C2013.cost.avg_net_price.overall%2C2013.completion.rate_suppressed.overall%2C2011.earnings.10_yrs_after_entry.median%2C2011.earnings.6_yrs_after_entry.percent_greater_than_25000%2Cschool.under_investigation&_debug=1

should have subsecond search_time in metadata

**Comment by yozlet** [comment]
This is now rather faster than it was, thanks to two suggestions from @GUI:
 
 1. In order to make the `fields` list only return the fields that were asked for, rather than entire documents, we needed to set `_source: false` in the query. This drastically reduces the amount of JSON coming back to the app, and so parsing is much faster.
 2. We're now using the [oj](https://github.com/ohler55/oj) JSON parser, which offers a significant speedup.

**Comment by ultrasaurus** [comment]
this is the PR that addressed this issue: https://github.com/18F/open-data-maker/pull/198

There's plenty more optimization to be had, but I think this issue should represent this specific fix

**Comment by ultrasaurus** [comment]
accepting since I think both @yozlet and I have verified the fix on staging
