### ISSUE TITLE
Retention rate needs to pull from either four- or less-than-four-year column

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1357]
For predominantly less-than-four-year schools that have retention rates in the four-year (RET_FT4) column, the site should pull in first the FTL4 retention rate and if that's NULL, then it should pull in the FT4 retention rate. This is already in place for completion rates.

For example: Aquinas College in Nashville, TN.

![image](https://cloud.githubusercontent.com/assets/13874735/10587775/c5844e6c-7670-11e5-9fe1-9765092ae7e2.png)

**Comment by ultrasaurus** [comment]
tested locally and this looks like it is fixed:

![image](https://cloud.githubusercontent.com/assets/41906/12495990/c4044daa-c047-11e5-93fb-9c872b4363d9.png)


Uses a client-side methodology, rather than the way completion rates are addressed server-side, but I think it is expedient and the right thing to do at the moment.  (It will allow us to deploy the fix without re-indexing.)

**Comment by ultrasaurus** [comment]
should it have a test?

**Comment by ultrasaurus** [comment]
this needs to be tested on staging by @barkimedes

**Comment by barkimedes** [comment]
Confirmed with Ed that it meets their expectations. LGTM :us:
