### ISSUE TITLE
As a researcher, I would like to know the last time the data was updated so that I can know if I need to download a more recent version.

### ISSUE THREAD

**Issue by barkimedes** [18F/college-choice#1360]
As a researcher, I would like to know the last time the data was updated so that I can know if I need to download a more recent version.

Related to #1359; see first comment. The general idea is that people often bulk download this data and cache it somewhere because it doesn't change very often. But they will want to know when it was last updated so that they know if it is worth downloading all of the data again.

I suspect if we do something on the API side to provide a last updated date (#1359), then this becomes a front end surfacing the data task. Not to get into implementation details here, but it probably makes sense to do #1359 first.

**Comment by yozlet** [comment]
The `data.json` endpoint (which reflects a JSON version of the `data.yml` file) _may_ be useful here. It's not currently documented. Example: https://ccapi-dev.18f.gov/v1/data.json

The most relevant field is the `version` field, which right now is a bit of a mess. It currently starts with `Aug27` because that's when we got the data dump from Ed, but followed by the ISO8601 date of the last time the file was updated. Rationalising this would save some work, especially since (AFAIK) we're going to stop using it to automatically trigger reindexing (thanks to some inbound work from @ultrasaurus). It'd definitely be worth splitting up to differentiate the age of the source data, the `data.yml` file and the index.

**Comment by yozlet** [comment]
Oops - just realised the above comment is more relevant to #1359. For this ticket, we could tweak the `data.json` endpoint so you can supply a path to a particular JSON key rather than having to download all 300Kb of it, and then the frontend can dynamically pull that? Maybe?

**Comment by ultrasaurus** [comment]
This is addressed with text on the website:
![image](https://cloud.githubusercontent.com/assets/41906/13652720/a3a038e0-e602-11e5-9167-bf953dffeebd.png)

**Comment by barkimedes** [comment]
looks good :us:
