### ISSUE TITLE
Figure out log retention/deletion

### ISSUE THREAD

**Issue by afeld** [18F/college-choice#1408]
Following the conversation at https://18f.slack.com/archives/collegechoice/p1451411251000121 ff. @ozzyjohnson Mind adding details with your recommended steps?

/cc https://github.com/18F/DevOps/issues/512

**Comment by abisker** [comment]
@ozzyjohnson: Can you provide clarity on how urgent this issue is?

**Comment by ozzyjohnson** [comment]
@abisker - Low urgency, high severity. 

It will take perhaps half a year or more for the production ES instance to fill up left untouched, but if / when it does queries will fail. Since the production school / city data is effectively read only, we don't stand to lose anything, but recovery would mean staging a new service instance and restoring / reindexing into it.

I'll flesh this out more later, but the gist of my recommendation is to...

1. Get familiar with [curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html)
1. Use curator via a service-proxy or cf-ssh session to snapshot / clean up the existing instance if necessary.
1. Build curator into the [elasticsearch](https://github.com/18F/docker-elasticsearch) and [elk](https://github.com/18F/elk-docker) images as a configurable cron job.
1. Have the cron above key off an environment variable which takes its default from the broker's plan definition to use whatever's required (90 / 180 days).
1. Configure the run-once instantiation scripts [elasticsearch](https://github.com/18F/docker-elasticsearch/blob/master/scripts/start.sh), [elk](https://github.com/18F/elk-docker/blob/master/start.sh) to persist that var.
1. [optional] Allow users to override that var as a [service parameter](https://docs.cloudfoundry.org/devguide/services/managing-services.html#arbitrary-params-update).
1. Have the CF operators run the `fetch-containers-images` errand to pull in the new service images. Recreate each elasticsearch / elk service after optionally backing up their indices with curator.
1. Restore.

**Comment by yozlet** [comment]
This is now a Cloud.gov issue rather than one for us, since they provide and maintain ES service as a standard system rather than a special thing for us. Have flagged this as something for them to double-check (though it's likely to be happening as part of their standard ops setup): https://github.com/18F/DevOps/issues/552

**Comment by afeld** [comment]
I think the original issue was around application logs, which are now automatically retained for 180 days automatically:

https://docs.cloud.gov/apps/logs/#historic-logs:6d6e87c8985e9c9e781f22ee066f5a45

Not sure about ElasticSearch logs though... will let one of the cloud.gov team answer in https://github.com/18F/DevOps/issues/552.

**Comment by afeld** [comment]
In other words, I'm not sure if there's a required retention period for ElasticSearch (non-web-server) logs, but if there is, that should be taken care of at the cloud.gov level, rather than something you will need to worry about within the College Choice application/configuration.

**Comment by LisaGee** [comment]
Waiting to hear from cloud.gov has resolved.

**Comment by NoahKunin** [comment]
It's resolved IMHO, at least without more detailed requirements from the CS team about the length of rotation and how much of a ElasticSearch history of the logs you require. I'd prefer that to be a freshly written issue though, with a specifics on the desired state - thanks!
