### ISSUE TITLE
As a Student, once I've executed a Search, I'd like to be able to click on anyplace in the school box to get more School details, so that is super easy for me to dive in deeper.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#241]
Each school "box" should be clickable in its entirety especially on Desktop. There should be an outline hover state for the whole box and I should be able to click anywhere within the box to get to the Details page.

**Comment by jjoteal** [comment]
I think this one should actually be reassigned to @meiqimichelle since it would need to be done via the front-end code. @meiqimichelle could we make the entire box clickable rather than just the name of the school and the "learn more" text? If so, I think a nice hover state would be a light gray dropshadow.

**Comment by meiqimichelle** [comment]
Yep, can-do!

**Comment by meiqimichelle** [comment]
@shawnbot I tried to fix this one but I think I'm not interacting with the data for the url to the indiv school in the right way. Would love to take a sec with you to see what's up.
