### ISSUE TITLE
Purchase hero image for consumer tool

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#33]
@jjoteal to put info here on which one we want

**Comment by meiqimichelle** [comment]
I'd like to move to the desktop layout for home. @LisaGee , should I purchase the stock image for now, or leave that space empty (placeholder) until the video testimonials? Or, someone can peruse https://unsplash.com/ to see if there's a free alternative.

**Comment by LisaGee** [comment]
I’m down to purchase an image or use a free one.

Fyi, Clare’s suggestions:
So this hopeful hero image might be…rising sun? Smiling students who are really enjoying studying for a test? Graduates throwing their caps? That kind of thing?

Let’s just make sure that it would be appealing to low-income, ethnically-diverse people ages 16-28 ☺
You got that, right?

**Comment by meiqimichelle** [comment]
Thanks for the info @LisaGee ! In that case, we should go with the stock photo that Jess already has in her design. It is a good one! I'll send you an email to get confirmation on record for the purchase.

**Comment by LisaGee** [comment]
Can I get y’all’s take on this image? It feels a little high falutin’ to me. Wondering if there might be a grittier, urban and hopeful image? I kind of like the idea of graduates (of all races) throwing their caps in the air. I think it also reinforces our message -> graduation is good!

**Comment by jjoteal** [comment]
Here are a few hero image alternatives (please note that these are watermarked images because i haven't purchased them, so they might appear a little blurry -- that problem won't exist once we purchase the image) . @LisaGee Let me know if you think any of these will work. Happy to keep searching as well.

![image](https://cloud.githubusercontent.com/assets/12192706/8605049/75f69f8c-2650-11e5-9faa-8ae1360136e1.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8605063/89812266-2650-11e5-8771-26d426214e42.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8605086/b47bf234-2650-11e5-9fe3-fefcacebfefa.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8605099/c9125b16-2650-11e5-8116-43fac52d2ea5.png)

**Comment by jjoteal** [comment]
@LisaGee @ErieMeyer -- Any feedback/choice on these hero image options?

**Comment by LisaGee** [comment]
I far and away like the first image the best (diverse happy graduates, yay!).

I like the hat throwing in the air concept, but not this image. Any chance we might be able to find another?

How much is image #1?

Shall we test it with our adult learners today and see if they see themselves reflected in the photo?

Thanks, Jess!

-Lisa

**Comment by jjoteal** [comment]
Image #1 is available here: http://www.istockphoto.com/photo/diverse-international-students-celebrating-graduation-37455484 and would be about $60 if you simply purchase via credits vs. a subscription. We can definitely ask our adult learners today for feedback on this image.

I can search for more cap-throwing images in the meantime. The pickins are a little slim...

**Comment by LisaGee** [comment]
Similar to these 2 is what I was thinking. But don’t know how hard to find as a stock image.

http://pictures.dealer.com/m/mazdaofelkgrove/1435/5b9a45c0b2283a68e4307594c34c693dx.jpg
http://www.clearpointcreditcounselingsolutions.org/wp-content/uploads/college-graduation.jpg

Or ideally this, if we made some of the skin various shades of brown: https://jamesrasbeary.files.wordpress.com/2015/05/college-graduation.jpg

What do you think? I really like the one you found with the diverse international students, I’m just wondering if people will relate more to photos that have faces or without?

--Lisa

**Comment by jjoteal** [comment]
Funny -- I just found those style of photos on the stock photography website that I use. Here they are laid out in context. I personally don't like these as much -- they feel a little cold to me because they take out the human element -- i.e. the "personal choice" component of the tool.

![image](https://cloud.githubusercontent.com/assets/12192706/8679774/b2ae77a0-2a2a-11e5-9ca3-0e0cded52cf1.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8679816/08c0505a-2a2b-11e5-812e-412288bc8c04.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8679907/acb63eb8-2a2b-11e5-91bc-5e0f7417b680.png)


I think images like these are better choices, but I still am leaning towards #1 above:

![image](https://cloud.githubusercontent.com/assets/12192706/8679921/c83a9166-2a2b-11e5-82d4-9bedac543d4e.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8679925/d322ec4a-2a2b-11e5-940c-9442f6c55dc2.png)

Thoughts?

**Comment by LisaGee** [comment]
I hear you and agree. I like the first one the best still.
https://cloud.githubusercontent.com/assets/12192706/8605049/75f69f8c-2650-11e5-9faa-8ae1360136e1.png

Let’s buy it and use it and we can get further feedback from ED, when they’re testing…

Thanks, Jess!

**Comment by meiqimichelle** [comment]
@LisaGee Thanks for the update! I just sent you an email to get official approval on record, and then I'll continue with purchase through 18F.

**Comment by jjoteal** [comment]
@meiqimichelle once you have purchased this photo, can you send to me? I need to do some color treatment work to it so it better matches the site color scheme.

**Comment by meiqimichelle** [comment]
Yes! Will do @jjoteal

**Comment by meiqimichelle** [comment]
@jjoteal Purchased! I put the photo in a new folder in the Design folder called Assets. So, PICC > Design > Assets.

**Comment by jjoteal** [comment]
@meiqimichelle I treated the purchased image and put the full resolution copy back up on the Drive. The file is hero-treated.jpg. Enjoy!

**Comment by meiqimichelle** [comment]
Closing as this purchase task is complete. Implementation is tracked in #322.
