### ISSUE TITLE
BUG/QUESTION: Can all the National Average lines be horizontally aligned at the exact middle of the bar graphs?

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#402]

**Comment by meiqimichelle** [comment]
A thought: when I see the current version, I think it is an interesting piece of information that an average might actually lie closer to the top or bottom of the range. It might be a false data munge to put all the average lines in the middle since the bars aren't things you can compare across, really.

However, I'd like to know about how the bars show up. Like, why are some national averages for graduation rate in different places? Was it that they're different based on 2- or 4-year schools?

**Comment by saintsoup52** [comment]
I definitely think the lines should not be in the middle of the graph.

The average grad for a 2 year school will be like 20% and putting the line in the middle would seriously skew the scale.

**Comment by LisaGee** [comment]
@jjoteal after our convo, do you think this makes sense? If so, can you close. If not, let's move it into research and play with the options a bit and see what ends up being most readable.
