### ISSUE TITLE
Get National Averages for the CT data points needed from Clare

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#493]
Needed for Launch. API set up to calculate Nat'l Averages will be post-Launch

**Comment by LisaGee** [comment]
See #271 for the API version of this story.

**Comment by LisaGee** [comment]
ALL schools in CT = 
•	PREDDEG==2 or 3
•	Not closed

1.	Median earnings – ALL Schools in CT
2.	Threshold earnings – ALL Schools in CT
3.	Completion Rate – 2 year schools (PREDDEG==2)
4.	Completion Rate – 4 year schools (PREDDEG==3)
5.	Completion Rate – ALL schools in CT 
6.	Net Price – Private Schools
7.	Net Price – Public Schools
8.	Net Price – ALL Schools in CT
9.	Monthly Student Loan Payments – ALL Schools in CT
10.	Repayment Rate – ALL Schools in CT
11.	Retention Rate – ALL Schools in CT

**Comment by saintsoup52** [comment]
Of all the emails I read over the weekend… I think this one has the most policy implications… because this is definitely a new yard stick schools are being measured against. And not that you asked… but I am going to offer my opinion on this anyways…

1)	Median Earnings (use - PREDDEG):  I think it is probably unfair to compare the earning capacity of a completer of an associates degree against a bachelor’s degree here. Especially when this will just strongly discourage against going to community colleges.

2)	Threshold Earnings (use - All schools): Since this a more universal measure, I think it is ok to compare all schools against a national average.

3)	Completion/Graduation Rates (use - PREDDEG): Tool should have separate national averages by the predominate degree awarded (same as scorecard)

4)	Net Price (use - PREDDEG): Should definitely NOT be separated by public/private. That will cause all sorts of data anomalies and mask expensive private schools. The scorecard currently separates by predominate degree and I think it that it should stay that way.

5)	Monthly Payments (use - PREDDEG): Comparing the monthly payment for a completer of a 4 year school against a completer of a 2 year school doesn’t make any sense. Of course the 2 year schools will look better here. They should continue to be done by predominate degree. 

6)	Repayment Rates (use - All schools): On the current scorecard default rates are compared against the national average for all schools. This makes sense to retain a comparison against all schools here.

7)	Retention Rate (use - All schools): This is a universal metric… it could be all schools or predominate degree type.

**Comment by LisaGee** [comment]
Thanks for this, Patrick.

Sent from my Windows Phone
________________________________

**Comment by LisaGee** [comment]
this is complete and implemented.
