### ISSUE TITLE
Need real Data Insights copy

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#498]
needs to be gotten from ED/DPC and entered into carousel that appears on the Data site.

**Comment by LisaGee** [comment]
@jjoteal Can you ping Clare and then enter the text?

**Comment by jjoteal** [comment]
@LisaGee -- FYI talked with Clare this morning about these. She needs to rework them as they were thinking Data Insights would have images (and they don't). I believe she also might be reaching out to you regarding prioritizing this...

**Comment by jjoteal** [comment]
Just an updated that I added all of these and submitted a PR. Crossing fingers that I didn't screw up too badly... Will find out once it's merged and will fix any issues at that point!

**Comment by jjoteal** [comment]
@LisaGee these are ready to review and accept:
https://federalist.18f.gov/preview/18F/college-choice/jjoteal-datainsights/data/

It is a little awkward because some quotes are long and some are short -- would be better to have similar length. Let me know if you'd like any edits or if you think we should only show 5 vs. 10....
