### ISSUE TITLE
As a member of the public/a developer I want to find data that is not available

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#527]
For items that say "Data not available" is there an engagement option for the public/developers who want to ask for that data?

Lots of good reasons why the data doesn't exist (regulatory changes, data collection changes, etc.)

Something like "ask the school" or "write your congressperson"? 

Not urgent, but if there's a way they could ask/advocate, that could be impactful.

**Comment by LisaGee** [comment]
Could it be asked on StackExchange? Or is that not an appropriate forum?

**Comment by ErieMeyer** [comment]
Oh! That's perfect. 

Thanks!

**Comment by saintsoup52** [comment]
Most of the data that is not collected is because of the type of school they are... for example graduate schools do not report graduation rates because grad rates are the number of undergrads who graduate.

If there was an ask for more data... it would probably be directed to ED or Congress or the like.

**Comment by ErieMeyer** [comment]
Thanks for engaging on this!
