### ISSUE TITLE
As a site operator, I'd like to have basic load testing to understand the concurrency limit at which we need to add more cloud resources

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#597]

**Comment by LisaGee** [comment]
@diego- @dnesting should ride shotgun.

**Comment by dnesting** [comment]
Does 18F have a load testing platform they tend to use?

**Comment by diego-** [comment]
no, product team tends to pick their favorite. Teams in the past have used siege, wrk, blitz.io, ab, etc.

**Comment by dnesting** [comment]
GIven that the consumer site is effectively hosted by S3, it seems like it's really api.data.gov that we're interested in, yes?  Possibly the open-data-maker component that sits behind it?  Who's a good contact for api.data.gov and I'll see what I can put together.

**Comment by diego-** [comment]
@dnesting correct; the API and corresponding origin server (open-data-maker instance) are the most important to load test since it powers the search functionality. @gbinal is our api.data.gov contact.

**Comment by dnesting** [comment]
Do we have an estimate of the traffic we expect on launch, and on a typical day?

**Comment by LisaGee** [comment]
Not for the API, as we cannot know how much traffic the 3rd party tools using are API will get.

@ErieMeyer @diego- - Maybe this is something we ask when the Devs come demo or should we just ask on the Beta list serve?

this would just be a jumping off point though....

**Comment by dnesting** [comment]
I think the right approach then is to test to find the current limits (as the original comment says) and then test again with some horizontal scaling.  If we can scale arbitrarily this way, it'll at least let us prove that out and give us a sense of what we need to have live.

**Comment by saintsoup52** [comment]
FYI-We had 500+ concurrent users on the GI Bill Comparison tool after VA sent an email out to all their vets.

**Comment by dnesting** [comment]
My current thought is to bring up "wrk" or similar (maybe @gbinal has a recommendation) in either Cloud Foundry or on AWS and have it hit ccapi-*.18f.gov with a representative sample of queries.  I think I need from someones:

- [ ] A representative sample of queries (or access to access logs so I can figure this out)
- [ ] Anything else I'll need to stick in a request to get responses (API key?)
- [ ] Identification of a specific ccapi instance that is configured the same as prod is/will be
- [ ] Find a way to access key system metrics (system utilization, requests/time) to monitor performance during the test

And then for part 2:

- [ ] Identify how we can scale that ccapi instance horizontally

And then for part 3:

- [ ] Confirm that api.data.gov is caching requests (find a cache hit metric?)
- [ ] Get comfortable with api.data.gov's scalability (either by doing testing or reviewing their previous results)

**Comment by ozzyjohnson** [comment]
>  Identify how we can scale that ccapi instance horizontally

The changes to identify a backing Elasticsearch instance over in [open-data-maker](https://github.com/18F/open-data-maker/issues/139) enable this. This allows the creation of multiple ccapi instances each pointing at its own elasticsearch.

Mapping a cf route such as `ccapi.18f.gov` to all of those ccapi instances will cause requests to be round-robin'd between them.

**Comment by ozzyjohnson** [comment]
> Find a way to access key system metrics (system utilization, requests/time) to monitor performance during the test

We have New Relic APM for the app and Marvel is available for Elasticsearch. New Relic has container-specific monitoring that might be applicable to Elasticsearch and the docker host, but I haven't taken a dig into it.

**Comment by dnesting** [comment]
@ozzyjohnson 

1. What do you think about configuring things now so that we can trivially scale out when the need arises?  What would be involved in that?  I'm happy doing the lifting here if I know what to do.
2. Can I get a New Relic account?  Or maybe I can just sit with someone when running the tests?

**Comment by ozzyjohnson** [comment]
@dnesting 

1. Depends on which bit we're talking about scaling out. 

I can create additional api instances and backing elasticsearch instances now. Though, that would be more like pre-scaling than making on demand scaling trivial. Trivial scaling requires creating a script or two that will spawn new elasticsearch instances and restore to them from a snapshot (Still not totally trivial as the data has be pulled from s3. Alternative would locating it closer or baking it in - not sure if either would be worth the effort) then creating a new api app instance and optionally adding a route.

2. Certainly. I'll invite you.

**Comment by dnesting** [comment]
Initial load testing results:
- The ccapi-ex instance can sustain about 70-75 responses per minute (1.1 requests per second)
- Increasing the number of requests per second just drives up response time

NewRelic screen shot:
![image](https://cloud.githubusercontent.com/assets/7342162/9741391/4947fbd6-5628-11e5-8b0d-530a182ec89c.png)

This depicts the tail of my testing and shows three clear periods: high response times (40 concurrent users), moderate (5 concurrent users), and low response times (1 concurrent user).  Note that for the same period, the actual transaction rate (requests/time) is constant around 70-75 r/min.

NR classifies most of the delay as "Request Queuing", which means the delay is introduced between the time nginx receives the request and marks the time, and when the NR plugin sees the same request during the execution pipeline and compares that time against the current time.

I'll work with @ozzyjohnson  to see what the infrastructure looks like between these two points and see what's what.

**Comment by dnesting** [comment]
The first bottleneck was in open-data-maker/config/unicorn.rb, where the number of Unicorn web server workers is established at 1.  Per the documentation at http://unicorn.bogomips.org/Unicorn/Configurator.html, the Unicorn web server only processes a single request at a time per worker.  If you double the number of concurrent requests, they're processed sequentially at double the response time.  This is consistent with the results above; the response time was lowest only at 1 concurrent request.

We experimented by increasing the number of workers to 5.  This required a large increase in the RAM limits for the instance (holding at about 2.7G of 3G).

![image](https://cloud.githubusercontent.com/assets/7342162/9744503/3647f7fe-563a-11e5-9e99-dfca87a1fcc0.png)

There are again three periods of time here: 1 concurrent request starting at about 11:10, which gives us the same ~60 requests/minute (as expected).  Increasing to 5 concurrent requests should have given us a 5x increase in the request rate while keeping response time the same.  In actuality, we only got a 2x increase in response rate with a 2.5x or so increase in response time.  This time the increase in response time is attributable to the Ruby code rather than queueing.  Increasing to 40 concurrent requests resulted in a large increase in response time attributed to request queueing (as before), in addition to the response time attributable to Ruby.

So I think we've hit a new bottleneck either in the Ruby code or elastic search behind it that's going to take some further research to identify.

**Comment by ErieMeyer** [comment]
Hello! We should check the heap settings because we may be maxing out memory on the node -- that's the most common elasticsearch failure, per a little birdie.

We should also ask @arowla

**Comment by awong-dev** [comment]
Random kibitz: Unicorn's scaling is pre-forking workers. http://unicorn.bogomips.org/PHILOSOPHY.html

This in general does bad things with spike loads and can cause thrashing when requests grow larger than number of cores available. (It's also more memory intensive due to process overhead).

Heroku pushes users to use puma. I suggest following their lead as an experiment.

(The graph on http://puma.io/ show unicorn server performance drop sharply around 40 concurrent requests which is characteristic of threaded servers.)

**Comment by dnesting** [comment]
Now load testing Puma instead of Unicorn.  To catch up, code changes were made to improve performance of Elastic Search queries.  This dropped the median search query from like 3s to around 150ms, which by itself (back at 1 worker) allowed the load test to see in excess of 500qpm overnight.

After switching to Puma, this doubled to about 1100qpm and with some tuning, I've settled on this configuration:

- 5 threads per worker (gives us good concurrency and seems to do a good job of maximizing usage of 1 vcpu)
- 3 workers per instance (spreads that usage pretty well across 2 vcpus given that most of the wallclock time is spent waiting on eservice)
- 3 instances (scaling seems roughly linear, and performance does not improve after this, suggesting we've hit a bottleneck that can't be addressed by scaling the app itself).

The resulting performance with this configuration is about 2400qpm (40qps) and our bottleneck now appears to be with elasticsearch (which is running at about 95% utilization of its 4 vcpus).  This strikes me as sufficient for our needs (if you figure one user will perform some request once every 10 seconds, this represents 400 users making requests that aren't cached by api.data.gov, so potentially we could scale to thousands of concurrent users if we assume we can get some good cache hit rates for the expensive searches, which we can do once we're comfortable with the caching).  I'm working with Ozzy now to come up with a plan to scale up the eservice further should the need arise, but I'm getting comfortable with the idea that we can scale up the app horizontally to continue to take advantage of the gains we can make there.

I'm focusing now on testing against api.data.gov.

**Comment by arowla** [comment]
:clap: If you need further help scaling Elasticsearch, the group formerly known as USASearch at GSA has experience there, and I can dig up a contact if need be.

**Comment by ultrasaurus** [comment]
Nice work @dnesting :clap:

**Comment by awong-dev** [comment]
@dnesting AWESOME.  Any chance you can stuff that write-up in a format that we can share with the wider digital service coallition?

Having a sane, recommended serving stack initial config sounds like something we should socialize.

**Comment by ErieMeyer** [comment]
🇺🇸🇺🇸🇺🇸☁️⚡️💪🏿

**Comment by dnesting** [comment]
I have pull request 18F/college-choice-data#7 outstanding with load testing documentation, after which I think this issue can be closed.

**Comment by LisaGee** [comment]
I think that means this story is ready for Accept.

**Comment by barkimedes** [comment]
Thank you @dnesting :us: :+1: :us:
