### ISSUE TITLE
ENHANCEMENT: Add scrollbar to list of Available Areas of Study so that it is obvious that you can scroll up and down in this area

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#635]
Mac Chrome (2:53pm)

Hard to tell that this a scrollable region:

![image](https://cloud.githubusercontent.com/assets/12192706/9502955/33be863e-4c02-11e5-8492-8b8597a0083d.png)

**Comment by meiqimichelle** [comment]
This is a bug. It should have one :-/

**Comment by LisaGee** [comment]
Should work on iPad too. See #787

**Comment by meiqimichelle** [comment]
This is a bit of an odd bird. As far as I can see on my end, it should be there (and I can't reproduce the error). However, we've gotten this report more than once. So, I've made it so that the scroll bar is *always* there. The downside is that even when the list is short, you get an empty scroll bar. Perhaps a fair trade. Looks like:

![screen shot 2015-09-05 at 4 06 14 pm](https://cloud.githubusercontent.com/assets/4827522/9701645/1d57f1bc-53e8-11e5-976e-ec77c9fe6a39.png)

and

![screen shot 2015-09-05 at 4 06 35 pm](https://cloud.githubusercontent.com/assets/4827522/9701648/2142c46e-53e8-11e5-8c42-cfe89ac20e17.png)

**Comment by ErieMeyer** [comment]
Hmmm -- on a mac, chrome. Still don't see the lil sidebar scrollie-do unless I'm over it and trying to scroll.

![screen shot 2015-09-07 at 11 10 48 am](https://cloud.githubusercontent.com/assets/1626026/9719324/308b0e80-5551-11e5-9578-5fabb710b8b6.png)
