### ISSUE TITLE
As a Developer, I'd like to be able to easily understand the Data Dictionary so it's more streamlined for me to make use of the API. 

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#738]
Clean up Data Dictionary for readibility.

**Comment by ultrasaurus** [comment]
From @diego- via email:  In order to make it easier to read, I want to reorder the columns so that the flow mimics the nested structure of the API calls. 

So for instance, 
(DATA ELEMENT NAME) (Year for Consumer Tool) (dev category) (developer-friendly name) (VARIABLE) 
etc.

The script uses column names, so re-ordering columns should be zero impact.  If you want to change the column names, that would imply a fairly simply script change.
