### ISSUE TITLE
ENHANCEMENT: Left Drawer UI Improvements

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#751]
Recommend changing the background color of the 'top bar' of the left drawer indicator to white like:
![image](https://cloud.githubusercontent.com/assets/12192706/9555617/354b0630-4d9c-11e5-9ec6-c592fb61969c.png)

Since the white background color will match the white background color of the drawer itself.

Also, recommend changing the hamburger menu icon to a close icon like:
![image](https://cloud.githubusercontent.com/assets/12192706/9555560/d109b946-4d9b-11e5-999b-08e298be6041.png)

When the drawer is open so it is more obvious to the user on how to close it (also, simply clicking out of the drawer should close it as well)

Also, would love to get folks' thoughts on having an interaction like:
https://www.google.com/design/spec/patterns/navigation-drawer.html

Where clicking on the hamburger icon brings the left drawer in front of the main content area as well as 'grays' out the main content area so that the focus is on the filters and search adjustments.

**Comment by meiqimichelle** [comment]
@jjoteal That 'gray out' was initially what I had, but decided that since we have filters in there that interactively interact with the content, people might want to still see the page. However, I think it makes it harder to understand that part of the page is 'gone' (opening the drawer pushes main content 'off screen' to the right on desktop) when the drawer is open if it's *not* grayed out. So, not sure. This would be, of course, a great place to test!

**Comment by jjoteal** [comment]
@meiqimichelle SOLD! on the fact that having the drawer open would allow folks to see what happens to the results in the main content area easier.

**Comment by meiqimichelle** [comment]
Closing in favor of #984
