### ISSUE TITLE
BUG: Calculate Your Exact Net Price opens to new tab

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#774]
Calculate new price opens college board website opens to new tab. (Chrome)

Macbook Pro Chrome
8/28/15 5 PM

**Comment by LisaGee** [comment]
@sharonleu - Hi Sharon, Can you specify what school you were looking at when you saw this issue? It would be great to include: URL of the page you were on, URL that you were sent to. Thanks.

**Comment by sharonleu** [comment]
Sorry - one of the early ones.  Clicking "Calculate Your Exact Net Price" and it went here.

<img width="977" alt="screen shot 2015-08-28 at 7 15 32 pm" src="https://cloud.githubusercontent.com/assets/14021544/9558903/4c06f542-4db9-11e5-8389-1ee437b3b41e.png">

**Comment by barkimedes** [comment]
The behavior I'm seeing now for some schools is that it just re-opens the same page in a new tab. For example, with https://collegescorecard.ed.gov/school/?117803-Los-Angeles-County-College-of-Nursing-and-Allied-Health. This looks like a bug; not sure what I expect other than perhaps a page saying "Calculate your personal net price" is not available for this institution rather than opening new tabs and redirecting back to the originating page.
