### ISSUE TITLE
Bug: Filter when page is on another page doesn't work

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#881]
Steps to repro:
1- Do an initial search for something that results in many pages of results
2- Navigate past the first page (try page 3 at least)
2- Open the filter pane
3- Filter by a school that you know exists
4- Notice that the page is empty

Here's the direct URL that gets generated for an example filter when we were on page 24 already:
https://college-choice.18f.gov/search/?name=Boston%20University&sort=advantage:desc&page=24

What it looks like:
<img width="600" alt="screenshot 2015-08-28 18 38 28" src="https://cloud.githubusercontent.com/assets/815256/9558520/bc006644-4db4-11e5-942f-0d0dbeb32b0f.png">

**Comment by LisaGee** [comment]
Need to figure out what UX should be when you are on page 15 of original search results, then user filters down to just 1 page of results. Automatically shift back to Page 1? What if filtered results still end up with 15 pages of new results - should the user still be directed back to page 1 or stay where they are?

**Comment by barkimedes** [comment]
@LisaGee Looks like current behavior is that if a filter is applied after you've browsed through some results, it will send you back to page 1. Which appears to address this specific problem.

But a separate (and in my opinion super not-worth-worrying-about) issue is that if you put in a page index into the url beyond where results show up, you see an empty page. 

To me, it seems like we can just close this bug and if someone else reports the other thing, we can deal with it then. Hope you agree, because that's what I'm doin' :us: :zap:
