### ISSUE TITLE
Alternate presentation to Advanced Search

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#890]
What if we:
1. Removed the Green Advanced Search Label.
2. Renamed the Institution Type Label to be Advanced Search.

![image](https://cloud.githubusercontent.com/assets/12847090/9560217/ad78c428-4dd6-11e5-8c41-f1ca70d952a8.png)

**Comment by meiqimichelle** [comment]
@jjoteal We've gotten various feedback on this part of the site. What do you think? We already renamed 'institution type' to 'advanced search'. Keep the green? Keep the not green? Toast advanced search entirely since there's only a few things under there right now, and move to be with the rest?

**Comment by meiqimichelle** [comment]
Ok! Looks like:

![screen shot 2015-09-02 at 8 24 43 am](https://cloud.githubusercontent.com/assets/4827522/9635694/89bb8ea2-514c-11e5-9a2a-a744c15c17e7.png)

What do you think of the name? It didn't make sense to call that section 'advanced search' anymore because there's nothing really obviously different or special about that section. `Type` seemed to cover it.

**Comment by ErieMeyer** [comment]
Love it! Looks great on dev.

**Comment by ErieMeyer** [comment]
Lgtm on staging
