### ISSUE TITLE
as a server, I would like to have cache control headers, so I don't need to respond to so many requests

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#990]
via Nick Muerdter:  We do provide an HTTP caching layer. However, your API must return the appropriate cache control headers if you want to perform caching (we don't cache anything by default). Here are the supported headers: http://apiumbrella.io/docs/caching/

**Comment by hollyallen** [comment]
Thoughts on this: will need to understand how we clear that cache when needed.

**Comment by hollyallen** [comment]
The api.data.gov cache doesn't have a programatic way to be cleared, though in a non-regular urgent use case they can clear it for us manually. This argues for short times to live, in case bad data ever gets into the cache. 

Adding @GUI so he can watch how this is implemented.

I recommend a time to live of 5 minutes. We don't expect our data to change, but we also don't want a long time to live on our cached results when we go live in case there is a problem and we want to fix to propagate quickly.

    Surrogate-Control: max-age=300
    Cache-Control: s-maxage=300
    Cache-Control: max-age=300 
    Expires: (HTTP date which is 300 seconds from NOW)

**Comment by LisaGee** [comment]
Agreed for launch. But let's say a week after, shouldn't we changed the TTL to actually make better use of the caching opportunity. The data will not change very frequently, probably once a year, but hopefully once a quarter. 5 mins seems a little ambitious. At my last gig, I made things that weren't really expected to change a TTL of 30 days. I'd be more comfortable, once we're settled that the data is in ok shape to make the TTL significantly longer. Is 1 week TTL just crazy talk?

**Comment by hollyallen** [comment]
@LisaGee I agree that when we have confidence in the lack of bugs/bad data getting into the cache, we should raise it to something like 7-30 days.

**Comment by ultrasaurus** [comment]
I agree with @hollyallen recommendation for today and maybe for launch --  load testing could reveal challenges which would cause us to make longer, certainly today keeping this short is important :)

**Comment by LisaGee** [comment]
Awesome. Sounds like we’re on the same page. Thanks!

**Comment by GUI** [comment]
And just to chime in here, all of this sounds like a good strategy to me too.

The only couple of things I'll add:

- Just to clarify, you shouldn't need to set all 4 of those HTTP cache headers at the same time:
  - `Cache-Control: max-age` and `Expires` effectively do the same thing, they are just two different conventions that achieve the same thing. So you should only need to use which ever one you prefer.
  - The other headers do subtly different things with intermediate caches, but they sort of bubble up, if that makes sense. As an example, `Cache-Control: max-age` will be used by client-side caches, ISP intermediate caches, and the api.data.gov cache, so if you want all those caches to use the same value, then that's the only header you need to set. Whereas, if you only wanted to allow caching by intermediate caches, but not the the client, then you could just set the `Cache-Control: s-maxage` header.
- If you eventually switch to much longer cache control times, just be aware that `Cache-Control: max-age`, `Cache-Control: s-maxage`, and `Expires` allow for caching by systems outside our control (for example, client-side caches or ISP-level caches). So if those headers are used and we force clear the api.data.gov cache, clients may still have content cached for the full duration and there's nothing you can really do about that (since we have no way of clearing their caches). If you want your cached results to always be controllable through what api.data.gov caches (which we can force clear for you), then you would only want to use the `Surrogate-Control` header. But if you also want to allow some client-side caching, you could also consider a hybrid approach like:

  ```
  Cache-Control: max-age=300
  Surrogate-Control: max-age=2419200
  ```

  This example would allow for the api.data.gov cache to cache results for 4 weeks, while allowing clients or other intermediate caches to cache results for 5 minutes. This kind of strategy can help minimize the amount of time external caches are allowed to cache things, while still allowing long cache durations in the api.data.gov cache which we can better control.

  (All that being said, I don't see a ton of intermediate caching done, and client-side caching is mainly an issue if the API requests will be made directly by browsers--if your users will mostly be developers consuming the API, then I don't see a lot of caching happening there, but it is possible.)

And as mentioned, we don't currently have the ability to allow for you to clear the api.data.gov cache on your own, but it's on our radar (https://github.com/18F/api.data.gov/issues/252). And in the meantime, you can ping one of the api.data.gov admins if you do need the cache cleared manually, and we're happy to do that on-demand.

**Comment by ultrasaurus** [comment]
started on this just understanding the Sinatra APIs for various headers... tagging @yozlet who is so fast with other things that he may be able to pick this up:  https://github.com/18F/open-data-maker/tree/dev-cache

**Comment by ultrasaurus** [comment]
@diego- @dnesting can one of you pls review this?

**Comment by dnesting** [comment]
All of this looks right to me.  I agree with the 5-minute thing initially.  There isn't much of a benefit to extending this to anything longer than a few hours or a day.  Setting it at one day, you're sparing the server a single request per day of any request made more often than once a day.  That's not going to be a lot of requests you're avoiding, versus the headache of caching any bad data we might discover in innumerable downstream caches.

**Comment by LisaGee** [comment]
Based on @dnesting 's review. Accepting.
